apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  namespace: esense
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    #nodePort: 30080
  selector:
    service: ambassador


