apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kronos-binding
  namespace: esense
  #name: kronos-binding-juno-089eb18d-vulcan-9d80182c-public-latest-gateway-0-31-0
  #namespace: juno-089eb18d-vulcan-9d80182c-public-latest-gateway-0-31-0
subjects:
  - kind: ServiceAccount
    name: default
    namespace: esense
    #namespace: juno-089eb18d-vulcan-9d80182c-public-latest-gateway-0-31-0
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io