apiVersion: v1
kind: Service
metadata:
  labels:
    service: venus
  name: venus
  namespace: esense
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: venus_mapping
      prefix: /
      service: venus
      timeout_ms: 15000
      cors: 
        origins: "*"
        methods: GET, POST, PUT, DELETE, OPTIONS
        headers: Authorization, Content-Type
spec:
  type: ClusterIP
  selector:
    app: venus
  ports:
  - port: 80
    targetPort: 80